import { TaskForm } from "@/components/TaskForm";
import { Title } from "@/components/Title";
import Link from "next/link";

export const metadata = {
  title: "New task",
  description: "Generated by create next app",
};

export default function NewTask() {
  return (
    <>
      <div className="flex  items-center justify-between">
        <Title
          title="Create Task"
          className="text-5xl font-bold min-xs:tracking-normal tracking-widest mt-[3rem] mb-[1.5rem] xs:my-[3.5rem] xs:text-7xl"
        />
        <Link href="/" className="bg-[#25b94a] p-2 rounded-md">
          {" "}
          🡰 Go back
        </Link>
      </div>

      <section>
        <TaskForm />
      </section>
    </>
  );
}
