import { getTasks } from "@/actions";
import { Search } from "@/components/Search";
import { TaskList } from "@/components/TaskList";
import { Title } from "@/components/Title";
import Link from "next/link";

export const metadata = {
  title: "List of tasks",
  description: "Generated by create next app",
};
type SearchParams = Promise<{ [key: string]: string | undefined }>;

export default async function Home(props: { searchParams: SearchParams }) {
  const searchParams = await props.searchParams;
  const { tasks } = await getTasks({
    query: searchParams.query,
    status: searchParams.status,
  });
  return (
    <>
      <Title
        title="List Task"
        className="text-5xl font-bold min-xs:tracking-normal tracking-widest mt-[3rem] mb-[1.5rem] xs:my-[3.5rem] xs:text-7xl"
      />
      <section>
        <Search />
      </section>
      <section className="p-[1rem] ">
        <Link href="/tasks/new-task" className="w-full h-full  hover:bg-[#50445f] transition ease-in-out duration-300">
          Create new task
        </Link>
      </section>
      <section className="my-4">
        <TaskList tasks={tasks} loading={false} />
      </section>

      <section className="flex items-center justify-center  gap-4 mt-3 p-[1rem]">
        <Link href="/">All</Link>
        <Link href="/?status=active">Active</Link>
        <Link href="/?status=completed">Completed</Link>
      </section>
    </>
  );
}
