import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Forit Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.className} relative antialiased min-h-screen flex flex-column justify-center max-w-[1440px] mx-auto`}
      >
        <header className="absolute  w-full top-0 left-0 flex align-center z-[-100] h-[200px] min-[376px]:h-[300px] bg-[url('/assets/images/bg-mobile-dark.jpg')] min-[376px]:bg-[url('/assets/images/bg-desktop-dark.jpg')] bg-no-repeat"></header>
        <main className="w-[90%] min-xs:w-full max-w-[400px]">{children}</main>
      </body>
    </html>
  );
}
